version: "3"
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  angular-fe:
    build:
      context: ./frontend/angular
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontend/angular:/app
    depends_on:
      - backend
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: simpleticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  react-fe:
    build:
      context: ./frontend/react-fe
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./frontend/react-fe:/app
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin-data: