# Generated by Django 4.1.4 on 2022-12-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('creationDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBys', related_query_name='createdBy', to=settings.AUTH_USER_MODEL)),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedBys', related_query_name='requestedBy', to=settings.AUTH_USER_MODEL)),
                ('requestedFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedFors', related_query_name='requestedFor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
